POST http://localhost:8080/book?title=ala ma kota&rating=5&description=Ciekawa książka&publisherId=1
###

GET http://localhost:8080/book/1
###

GET http://localhost:8080/books
###

PUT http://localhost:8080/book/1?title=ala ma kota Filemona z czarną łapką&rating=8&description=Ciekawa książka o kocie Filemonie
###

DELETE http://localhost:8080/book/1
###

GET http://localhost:8080/books?rating=5
###

GET http://localhost:8080/books/publisher
###

GET http://localhost:8080/books/?publisherId=2
###

GET http://localhost:8080/books/?authorId=2
###